title: Campamentos Patrones Hermosos
description: Documentaci√≥n para realizar un campamento con Patrones Hermosos.
theme: just-the-docs

url: https://patroneshermosos-oficial/bootcamps-docs.github.io

aux_links:
  Template Repository: https://github.com/patroneshermosos-oficial/bootcamps-docs
